[package]
name = "keylogger-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rdev = "0.5.3"
lazy_static = "1.4.0"
reqwest = { version = "0.12.7", features = ["blocking"] }
tokio = { version="1", features = ["full"] }
warp = "0.3.7"